#if !defined(AFX_MOTIONSENSOR_H__9B1B14BF_BF5D_427B_9686_A9336E1821CD__INCLUDED_)
#define AFX_MOTIONSENSOR_H__9B1B14BF_BF5D_427B_9686_A9336E1821CD__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

#include "TOPOSMotionSensor.h"

/////////////////////////////////////////////////////////////////////////////
// CMotionSensorWrapper wrapper class
//TAR251360  Modified this class to be like the other wrapper classes, less
//tightly linked to the actual CO's methods, and using progid, in the .cpp, to
//create the control.  This should make this device less prone to churn through
//OCX or SO changes.
class CMotionSensorWrapper : public TOPOSMotionSensor<CGenericOposIF>
{
   public:  
      static TClassPtr<CGenericOposIF> CreateDevice( HKEY hKey, long nDeviceId )
         { return new CMotionSensorWrapper( nDeviceId ); }
      virtual CMotionSensorWrapper* GetMotionSensor( void ) { return this; }
      virtual void OnOposStatusEvent( long nStatus );
   public:
	   BOOL Create( CWnd* pParentWnd, UINT nID );
   public:  // pure virtuals from CGenericOposIF
      virtual long GetDeviceClass( void ) const 
         { return DMCLASS_MOTION_SENSOR; }
	  virtual long CheckHealth( long lLevel );	
	  void EnableCouponProcessing(bool bFlag);
	   
private:
	  CMotionSensorWrapper( long nDeviceId ):m_bPostCouponEventFlag(false), m_bIsSensorBlocked (false)
	  { m_nDeviceId = nDeviceId; }
	  bool m_bPostCouponEventFlag;		
	  bool m_bIsSensorBlocked;

};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MOTIONSENSOR_H__9B1B14BF_BF5D_427B_9686_A9336E1821CD__INCLUDED_)
