#pragma once

typedef enum
{
	STCHG_REASON_TIMEOUT,
   STCHG_REASON_GOBACK,
   STCHG_REASON_RETURNACHORSTATE
} STCHG_REASON;


// These names are NOT any arbitrary names that we would like.
// Take special care to verify that these are the names that RUNTIME_CLASS macros generate and use.
// If not, the mapping mechanism will fail.
//#define RTCLASSNAME_SMFINISH					"SMFinish"
//#define RTCLASSNAME_SMCONTINUETRANS			"SMContinueTrans"
//#define RTCLASSNAME_SMCASHPAYMENT			"SMCashPayment"
//#define RTCLASSNAME_SMINPROGRESS				"SMInProgress"
//#define RTCLASSNAME_SCANANDBAG				"SMScanAndBag"
//#define RTCLASSNAME_SWIPECARD 				"SMSwipeCard"
//#define RTCLASSNAME_OPENACCNUM 				"SMEnterAlphaNumericInfo"
//#define RTCLASSNAME_INPROGRESS 				"SMInProgress"
//#define RTCLASSNAME_CARDPROCESSING  		"SMCardProcessing"
//#define RTCLASSNAME_ENTERCID          		"SMEnterAMEXCID"
//#define RTCLASSNAME_ASSISTMODE        		"SMSmAssistMode"
//#define RTCLASSNAME_ATTRACT             "SMAttract"




#define RTCLASSNAME_SMAcknowledgeSig                 "SMAcknowledgeSig"
#define RTCLASSNAME_SMAssistedTender                 "SMAssistedTender"
#define RTCLASSNAME_SMAttract                        "SMAttract"
#define RTCLASSNAME_SMBagAndEAS                      "SMBagAndEAS"
#define RTCLASSNAME_SMCardMisRead                    "SMCardMisRead"
#define RTCLASSNAME_SMCardProcessing                 "SMCardProcessing"
#define RTCLASSNAME_SMCashPayment                    "SMCashPayment"
#define RTCLASSNAME_SMCheckBasketReminder            "SMCheckBasketReminder"
#define RTCLASSNAME_SMCmDataEntry                    "SMCmDataEntry"
#define RTCLASSNAME_SMConfirmAbort                   "SMConfirmAbort"
#define RTCLASSNAME_SMConfirmDebitAmount             "SMConfirmDebitAmount"
#define RTCLASSNAME_SMConfirmEBTAmount               "SMConfirmEBTAmount"
#define RTCLASSNAME_SMConfirmQuantity                "SMConfirmQuantity"
#define RTCLASSNAME_SMConfirmSignature               "SMConfirmSignature"
#define RTCLASSNAME_SMConfirmVoid                    "SMConfirmVoid"
#define RTCLASSNAME_SMContextHelp                    "SMContextHelp"
#define RTCLASSNAME_SMContinueTrans                  "SMContinueTrans"
#define RTCLASSNAME_SMCopyPay                        "SMCopyPay"
#define RTCLASSNAME_SMCopyPayError                   "SMCopyPayError"
#define RTCLASSNAME_SMCouponNoMatch                  "SMCouponNoMatch"
#define RTCLASSNAME_SMCouponNotAllowed               "SMCouponNotAllowed"
#define RTCLASSNAME_SMCouponTooHigh                  "SMCouponTooHigh"
#define RTCLASSNAME_SMCrateableItem                  "SMCrateableItem"
#define RTCLASSNAME_SMCustomMessage                  "SMCustomMessage"
#define RTCLASSNAME_SMDepositCoupons                 "SMDepositCoupons"
#define RTCLASSNAME_SMDropoffCoupons                 "SMDropoffCoupons"
#define RTCLASSNAME_SMElectronicBenefitsTransfer     "SMElectronicBenefitsTransfer"
#define RTCLASSNAME_SMEnterAMEXCID                   "SMEnterAMEXCID"
#define RTCLASSNAME_SMEnterAlphaNumericInfo          "SMEnterAlphaNumericInfo"
#define RTCLASSNAME_SMEnterCashValue                 "SMEnterCashValue"
#define RTCLASSNAME_SMEnterCouponValue               "SMEnterCouponValue"
#define RTCLASSNAME_SMEnterCoupons                   "SMEnterCoupons"
#define RTCLASSNAME_SMEnterPin                       "SMEnterPin"
#define RTCLASSNAME_SMEnterQuantity                  "SMEnterQuantity"
#define RTCLASSNAME_SMEnterWeight                    "SMEnterWeight"
#define RTCLASSNAME_SMEnterWtForPriceEmbedded        "SMEnterWtForPriceEmbedded"
#define RTCLASSNAME_SMFinish                         "SMFinish"
#define RTCLASSNAME_SMGetFoodStampState              "SMGetFoodStampState"
#define RTCLASSNAME_SMHardTagItemWarning             "SMHardTagItemWarning"
#define RTCLASSNAME_SMHelpModeState                  "SMHelpModeState"
#define RTCLASSNAME_SMHelpOnWay                      "SMHelpOnWay"
#define RTCLASSNAME_SMInProgress                     "SMInProgress"
#define RTCLASSNAME_SMInSAProgress                   "SMInSAProgress"
#define RTCLASSNAME_SMInsertCoupon                   "SMInsertCoupon"
#define RTCLASSNAME_SMItemNotForSale                 "SMItemNotForSale"
#define RTCLASSNAME_SMItemQuantityExceeded           "SMItemQuantityExceeded"
#define RTCLASSNAME_SMKeyInCode                      "SMKeyInCode"
#define RTCLASSNAME_SMLaneClosed                     "SMLaneClosed"
#define RTCLASSNAME_SMLimitedEBTBenefit              "SMLimitedEBTBenefit"
#define RTCLASSNAME_SMLookUpItem                     "SMLookUpItem"
#define RTCLASSNAME_SMOperatorPasswordState          "SMOperatorPasswordState"
#define RTCLASSNAME_SMOutOfService                   "SMOutOfService"
#define RTCLASSNAME_SMOutOfService2                  "SMOutOfService2"
#define RTCLASSNAME_SMPickingUpItems                 "SMPickingUpItems"
#define RTCLASSNAME_SMProcessing                     "SMProcessing"
#define RTCLASSNAME_SMProduceFavorites               "SMProduceFavorites"
#define RTCLASSNAME_SMPromotionalSavings             "SMPromotionalSavings"
#define RTCLASSNAME_SMRAPDataNeeded                  "SMRAPDataNeeded"
#define RTCLASSNAME_SMRequestSig                     "SMRequestSig"
#define RTCLASSNAME_SMRestrictedNotAllowed           "SMRestrictedNotAllowed"
#define RTCLASSNAME_SMRewardOrRetrieval              "SMRewardOrRetrieval"
#define RTCLASSNAME_SMScaleBroken                    "SMScaleBroken"
#define RTCLASSNAME_SMScanAndBag                     "SMScanAndBag"
#define RTCLASSNAME_SMScanCard                       "SMScanCard"
#define RTCLASSNAME_SMSecBagAreaBackup               "SMSecBagAreaBackup"
#define RTCLASSNAME_SMSecBagBoxThreshold             "SMSecBagBoxThreshold"
#define RTCLASSNAME_SMSecItemRemovedThreshold        "SMSecItemRemovedThreshold"
#define RTCLASSNAME_SMSecMisMatchWeight              "SMSecMisMatchWeight"
#define RTCLASSNAME_SMSecNewItemEntry                "SMSecNewItemEntry"
#define RTCLASSNAME_SMSecOperatorPWState             "SMSecOperatorPWState"
#define RTCLASSNAME_SMSecSkipBaggingThreshold        "SMSecSkipBaggingThreshold"
#define RTCLASSNAME_SMSecUnExpectedIncrease          "SMSecUnExpectedIncrease"
#define RTCLASSNAME_SMSecUnexpectedDecrease          "SMSecUnexpectedDecrease"
#define RTCLASSNAME_SMSecurityLevel2                 "SMSecurityLevel2"
#define RTCLASSNAME_SMSecurityLevel3                 "SMSecurityLevel3"
#define RTCLASSNAME_SMSelectCardType                 "SMSelectCardType"
#define RTCLASSNAME_SMSelectContainer                "SMSelectContainer"
#define RTCLASSNAME_SMSelectDebitType                "SMSelectDebitType"
#define RTCLASSNAME_SMSelectFromList                 "SMSelectFromList"
#define RTCLASSNAME_SMSelectPayment                  "SMSelectPayment"
#define RTCLASSNAME_SMSelectTare                     "SMSelectTare"
#define RTCLASSNAME_SMSetAllItemsAside               "SMSetAllItemsAside"
#define RTCLASSNAME_SMSignCharge                     "SMSignCharge"
#define RTCLASSNAME_SMSmAbort                        "SMSmAbort"
#define RTCLASSNAME_SMSmAborted                      "SMSmAborted"
#define RTCLASSNAME_SMSmAssistMode                   "SMSmAssistMode"
#define RTCLASSNAME_SMSmAuthorization                "SMSmAuthorization"
#define RTCLASSNAME_SMSmConfirmSuspendedTransaction  "SMSmConfirmSuspendedTransaction"
#define RTCLASSNAME_SMSmCouponItems                  "SMSmCouponItems"
#define RTCLASSNAME_SMSmDataEntry                    "SMSmDataEntry"
#define RTCLASSNAME_SMSmEnterBirthdate               "SMSmEnterBirthdate"
#define RTCLASSNAME_SMSmManagerID                    "SMSmManagerID"
#define RTCLASSNAME_SMSmManagerPWD                   "SMSmManagerPWD"
#define RTCLASSNAME_SMSmMediaStatus                  "SMSmMediaStatus"
#define RTCLASSNAME_SMSmOutOfService                 "SMSmOutOfService"
#define RTCLASSNAME_SMSmReportsMenu                  "SMSmReportsMenu"
#define RTCLASSNAME_SMSmRestrictedItems              "SMSmRestrictedItems"
#define RTCLASSNAME_SMSmSecurityLogs                 "SMSmSecurityLogs"
#define RTCLASSNAME_SMSmSystemFunctions              "SMSmSystemFunctions"
#define RTCLASSNAME_SMSmVisualItems                  "SMSmVisualItems"
#define RTCLASSNAME_SMSmVoidedItems                  "SMSmVoidedItems"
#define RTCLASSNAME_SMSmmAddWeight                   "SMSmmAddWeight"
#define RTCLASSNAME_SMSmmEditAdd                     "SMSmmEditAdd"
#define RTCLASSNAME_SMSmmEditWtExp                   "SMSmmEditWtExp"
#define RTCLASSNAME_SMSmmEditWtSubCk                 "SMSmmEditWtSubCk"
#define RTCLASSNAME_SMSmmEditWtTolerance             "SMSmmEditWtTolerance"
#define RTCLASSNAME_SMSmmInvalidWtTol                "SMSmmInvalidWtTol"
#define RTCLASSNAME_SMSmmKeyInWtTol                  "SMSmmKeyInWtTol"
#define RTCLASSNAME_SMStaplesCoupons                 "SMStaplesCoupons"
#define RTCLASSNAME_SMStaplesCouponsError            "SMStaplesCouponsError"
#define RTCLASSNAME_SMStaplesNumberOfCopies          "SMStaplesNumberOfCopies"
#define RTCLASSNAME_SMStaplesSelectPaperSize         "SMStaplesSelectPaperSize"
#define RTCLASSNAME_SMStaplesSelectPaperType         "SMStaplesSelectPaperType"
#define RTCLASSNAME_SMState                          "SMState"
#define RTCLASSNAME_SMStoreModeState                 "SMStoreModeState"
#define RTCLASSNAME_SMSuspend                        "SMSuspend"
#define RTCLASSNAME_SMSwipeCard                      "SMSwipeCard"
#define RTCLASSNAME_SMSwipeCardAsItem                "SMSwipeCardAsItem"
#define RTCLASSNAME_SMSystemMessage                  "SMSystemMessage"
#define RTCLASSNAME_SMSystemMessage1                 "SMSystemMessage1"
#define RTCLASSNAME_SMSystemMessage2                 "SMSystemMessage2"
#define RTCLASSNAME_SMSystemMessage3                 "SMSystemMessage3"
#define RTCLASSNAME_3SystemMessage4                  "SMSystemMessage4"
#define RTCLASSNAME_SMSystemMessage5                 "SMSystemMessage5"
#define RTCLASSNAME_3SystemMessage6                  "SMSystemMessage6"
#define RTCLASSNAME_SMSystemMessageOpPass            "SMSystemMessageOpPass"
#define RTCLASSNAME_SMTakeCard                       "SMTakeCard"
#define RTCLASSNAME_SMTakeChange                     "SMTakeChange"
#define RTCLASSNAME_SMTakeLoyaltyCard                "SMTakeLoyaltyCard"
#define RTCLASSNAME_SMTakeReceipt                    "SMTakeReceipt"
#define RTCLASSNAME_SMTaxExemptions                  "SMTaxExemptions"
#define RTCLASSNAME_SMTaxExemptionsInputError        "SMTaxExemptionsInputError"
#define RTCLASSNAME_SMThankYou                       "SMThankYou"
#define RTCLASSNAME_SMTimeRestrictedItem             "SMTimeRestrictedItem"
#define RTCLASSNAME_SMTransportItem                  "SMTransportItem"
#define RTCLASSNAME_SMUnDeActivatedItemApproval      "SMUnDeActivatedItemApproval"
#define RTCLASSNAME_SMUnknownItem                    "SMUnknownItem"
#define RTCLASSNAME_SMUnknownPrice                   "SMUnknownPrice"
#define RTCLASSNAME_SMVoidApproval                   "SMVoidApproval"
#define RTCLASSNAME_SMVoidItem                       "SMVoidItem"
#define RTCLASSNAME_SMVoidNoMatch                    "SMVoidNoMatch"
#define RTCLASSNAME_SMVoidTransApproval              "SMVoidTransApproval"
#define RTCLASSNAME_SMWaitForApproval                "SMWaitForApproval"
#define RTCLASSNAME_SMWaitForRemoteAssistance        "SMWaitForRemoteAssistance"
