// TelnetClientSupport.idl : IDL source for TelnetClientSupport.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (TelnetClientSupport.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(1E457639-943F-4D9A-A765-07D264FE6ECB),
		dual,
		helpstring("ITelnetClientIF Interface"),
		pointer_default(unique)
	]
	interface ITelnetClientIF : IDispatch
	{
		[id(1), helpstring("method SetCallback")] HRESULT SetCallback([in] VARIANT pfnCallbackAddr);
		[id(2), helpstring("method ReceiveString")] HRESULT ReceiveString([out]BSTR *bstrInputString, [in]long lCharCount);
		[id(3), helpstring("method TransmitString")] HRESULT TransmitString([in] BSTR bstrSendString);
		[id(4), helpstring("method Connect")] HRESULT Connect([in] BSTR bstrHostName, [in]long lPortNum);
		[id(5), helpstring("method Disconnect")] HRESULT Disconnect();
	};

[
	uuid(BDF72F9B-5259-4A1C-B605-7536E33B9BB5),
	version(1.0),
	helpstring("TelnetClientSupport 1.0 Type Library")
]
library TELNETCLIENTSUPPORTLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(2A7DDE01-8012-47F5-A3C6-4000CDF26C27),
		helpstring("TelnetClientIF Class")
	]
	coclass TelnetClientIF
	{
		[default] interface ITelnetClientIF;
	};
};
