#pragma once

class ACS
{
public:
	static LPCTSTR OPT_APPMODEL;
	static LPCTSTR OPT_APPMODEL_DEF;
	static LPCTSTR OPT_FINALAPPMODEL; 
	static LPCTSTR OPT_FINALAPPMODEL_DEF;
	static LPCTSTR OPT_ACSIODLL;
	static LPCTSTR OPT_ACSIODLL_DEF;
	static LPCTSTR OPT_ACSEXFUNCSDLL;
	static LPCTSTR OPT_ACSEXFUNCSDLL_DEF;
	static LPCTSTR OPT_OPERATOR;
	static LPCTSTR OPT_PASSWORD;
	static LPCTSTR OPT_ACSIO_QUEUE_ENTRIES;
	static LPCTSTR OPT_ACSIO_QUEUE_ENTRIES_DEF;
	static LPCTSTR OPT_OPOS_LISTENTODEVICES;
	static LPCTSTR OPT_OPOS_LISTENTODEVICES_DEF;
	static LPCTSTR OPT_APPLICATIONNAME;
	static LPCTSTR OPT_APPLICATIONNAME_DEF;
	static LPCTSTR OPT_AUXMSG_ISEQ;
	static LPCTSTR OPT_AUXMSG_ISEQ_DEF;
	static LPCTSTR OPT_AUXMSG_PROP;
	static LPCTSTR OPT_AUXMSG_PROP_DEF;
	static LPCTSTR OPT_AUXMSG_ID_PROP;
	static LPCTSTR OPT_AUXMSG_ID_PROP_DEF;

};
