#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CRemoteConsoleMgrWrapper wrapper class

class CRemoteConsoleMgrWrapper : public CWnd
{
protected:
	DECLARE_DYNCREATE(CRemoteConsoleMgrWrapper)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xB9897549, 0xF1B, 0x4F36, { 0xB3, 0x74, 0x64, 0x58, 0x43, 0xC0, 0xB5, 0x83 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName, LPCTSTR lpszWindowName, DWORD dwStyle,
						const RECT& rect, CWnd* pParentWnd, UINT nID, 
						CCreateContext* pContext = NULL)
	{ 
		return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); 
	}

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle, const RECT& rect, CWnd* pParentWnd, 
				UINT nID, CFile* pPersist = NULL, BOOL bStorage = FALSE,
				BSTR bstrLicKey = NULL)
	{ 
		return CreateControl(/*GetClsid()*/_T("REMOTECONSOLEMGR.RemoteConsoleMgrCtrl.1"), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); 
	}

// Attributes
public:


// Operations
public:

// _DRemoteConsoleMgr

// Functions
//

long Initialize(long pPSX)
{
	long result;
	static BYTE parms[] = VTS_I4 ;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_I4, (void*)&result, parms, pPSX);
	return result;
}
long Terminate()
{
	long result;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}
long CanApprove(LPCTSTR bstrInParms, long * pResult)
{
	long result;
	static BYTE parms[] = VTS_BSTR VTS_PI4 ;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_I4, (void*)&result, parms, bstrInParms, pResult);
	return result;
}
long GetApprovalInfo(LPCTSTR bstrInParms, BSTR * pbstrOutParms)
{
	long result;
	static BYTE parms[] = VTS_BSTR VTS_PBSTR ;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_I4, (void*)&result, parms, bstrInParms, pbstrOutParms);
	return result;
}
long OnControl(LPCTSTR bstrInParms, BSTR * pbstrOutParms)
{
	long result;
	static BYTE parms[] = VTS_BSTR VTS_PBSTR ;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_I4, (void*)&result, parms, bstrInParms, pbstrOutParms);
	return result;
}
long OnEvent(LPCTSTR bstrInParms)
{
	long result;
	static BYTE parms[] = VTS_BSTR ;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_I4, (void*)&result, parms, bstrInParms);
	return result;
}
long Get(LPCTSTR bstrInParms, BSTR * pbstrOutParms)
{
	long result;
	static BYTE parms[] = VTS_BSTR VTS_PBSTR ;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_I4, (void*)&result, parms, bstrInParms, pbstrOutParms);
	return result;
}
long Set(LPCTSTR bstrInParms)
{
	long result;
	static BYTE parms[] = VTS_BSTR ;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_I4, (void*)&result, parms, bstrInParms);
	return result;
}
long OnApproval(LPCTSTR bstrInParms)
{
	long result;
	static BYTE parms[] = VTS_BSTR ;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_I4, (void*)&result, parms, bstrInParms);
	return result;
}
long OnInputEvent(LPCTSTR bstrInParms)
{
	long result;
	static BYTE parms[] = VTS_BSTR ;
	InvokeHelper(0x0a, DISPATCH_METHOD, VT_I4, (void*)&result, parms, bstrInParms);
	return result;
}

// Properties
//



};
