#if !defined(AFX_CLIENTDBMGR_H__93D3C210_EAA8_11D5_AE33_00E02930222C__INCLUDED_)
#define AFX_CLIENTDBMGR_H__93D3C210_EAA8_11D5_AE33_00E02930222C__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CClientDBMgr wrapper class

class CClientDBMgr : public CWnd
{
protected:
	DECLARE_DYNCREATE(CClientDBMgr)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xd96bc86b, 0xcef9, 0x11d5, { 0x81, 0x5e, 0x0, 0x90, 0x27, 0x81, 0xad, 0x16 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long StartItemLookup(LPDISPATCH pWTInfoObj);
	long LastChanceLookup(LPDISPATCH pWTInfoObj);
	long GetDeptException(LPCTSTR DeptID, LPDISPATCH pWTInfoObj);
	long SetUp();
	long GetStatus();
	long UpdateException(LPDISPATCH pWTInfoObj);
	long UpdateWLDB(LPDISPATCH pWTInfoObj);
	long TESTStartItemLookup(LPCTSTR csUPC);
	long TESTLastChanceLookup(LPCTSTR csUPC);
	long QuerySMMTol(LPCTSTR csUPC, long lDept, long lTolType, long lPPWU);
	long QuerySMMWLDBwt(LPCTSTR csUPC, long lDept, LPCTSTR csDesc, long lPrice, long lSpecialItem, long lPPWU);
	long UpdateSMMTol(long lAction, LPCTSTR csUPC, long lDept, long lTolType, long lWtExp, long lWtSubCk, long lWtTol, long lPPWU);
	long UpdateSMMWLDBwt(long lAction, LPCTSTR csUPC, long lDept, long lBSwt, long lAppr, long lTally, long lDate, long lInitWt, long lPPWU);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CLIENTDBMGR_H__93D3C210_EAA8_11D5_AE33_00E02930222C__INCLUDED_)
