// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "ncrsscodigitalreceiptgen.h"

/////////////////////////////////////////////////////////////////////////////
// CNCRSSCODigitalReceiptGen

IMPLEMENT_DYNCREATE(CNCRSSCODigitalReceiptGen, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CNCRSSCODigitalReceiptGen properties

CString CNCRSSCODigitalReceiptGen::GetBottomLogo()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CNCRSSCODigitalReceiptGen::SetBottomLogo(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

CString CNCRSSCODigitalReceiptGen::GetFormattedReceiptFilename()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CNCRSSCODigitalReceiptGen::SetFormattedReceiptFilename(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

CString CNCRSSCODigitalReceiptGen::GetHTMLFont()
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CNCRSSCODigitalReceiptGen::SetHTMLFont(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

CString CNCRSSCODigitalReceiptGen::GetLastReceiptFilename()
{
	CString result;
	GetProperty(0x4, VT_BSTR, (void*)&result);
	return result;
}

void CNCRSSCODigitalReceiptGen::SetLastReceiptFilename(LPCTSTR propVal)
{
	SetProperty(0x4, VT_BSTR, propVal);
}

CString CNCRSSCODigitalReceiptGen::GetPresetBitmap1()
{
	CString result;
	GetProperty(0x5, VT_BSTR, (void*)&result);
	return result;
}

void CNCRSSCODigitalReceiptGen::SetPresetBitmap1(LPCTSTR propVal)
{
	SetProperty(0x5, VT_BSTR, propVal);
}

CString CNCRSSCODigitalReceiptGen::GetTopLogo()
{
	CString result;
	GetProperty(0x6, VT_BSTR, (void*)&result);
	return result;
}

void CNCRSSCODigitalReceiptGen::SetTopLogo(LPCTSTR propVal)
{
	SetProperty(0x6, VT_BSTR, propVal);
}

CString CNCRSSCODigitalReceiptGen::GetPresetBitmap2()
{
	CString result;
	GetProperty(0x7, VT_BSTR, (void*)&result);
	return result;
}

void CNCRSSCODigitalReceiptGen::SetPresetBitmap2(LPCTSTR propVal)
{
	SetProperty(0x7, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CNCRSSCODigitalReceiptGen operations

CString CNCRSSCODigitalReceiptGen::GenerateDigitalReceipt()
{
	CString result;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CNCRSSCODigitalReceiptGen::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
