#if !defined(AFX_SMARTSCALE_H__918C5A9B_849D_4FE8_99ED_1E342359F7AA__INCLUDED_)
#define AFX_SMARTSCALE_H__918C5A9B_849D_4FE8_99ED_1E342359F7AA__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSmartScale wrapper class

class CSmartScale : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSmartScale)
public:
	//+TAR251360 - eliminated ClsId for SmartScale to prevent confusion in the future.
	LPCTSTR GetProgid()
	{
		static TCHAR progid[] = _T("SMARTSCALE.SmartScaleCtrl.1");
		return progid;

	}

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetProgid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
				pPersist, bStorage, bstrLicKey); }
	//-TAR251360 - eliminated ClsId for SmartScale
// Attributes
public:
	long GetSlowConclusionTimeout();
	void SetSlowConclusionTimeout(long);
	long GetSCWatchdogTimeout();
	void SetSCWatchdogTimeout(long);
	long GetZeroWeightTimeout();
	void SetZeroWeightTimeout(long);
	long GetLastGoodWeight();
	void SetLastGoodWeight(long);
	BOOL GetHoldWeight();
	void SetHoldWeight(BOOL);
	BOOL GetSkipBagging();
	void SetSkipBagging(BOOL);
	long GetHeavyWeightLimit();
	void SetHeavyWeightLimit(long);
	long GetMeduimWeightLimit();
	void SetMeduimWeightLimit(long);
	long GetHeavyWeightTol();
	void SetHeavyWeightTol(long);
	long GetMediumWeightTol();
	void SetMediumWeightTol(long);
	long GetLightWeightTol();
	void SetLightWeightTol(long);
	long GetCurrentTotalWeight();
	void SetCurrentTotalWeight(long);
	long GetNewItemZeroWeightTimeout();
	void SetNewItemZeroWeightTimeout(long);
	long GetSlowConclusionTimeoutInAttract();
	void SetSlowConclusionTimeoutInAttract(long);
	long GetSlowConclTimeoutInNotExpecting();
	void SetSlowConclTimeoutInNotExpecting(long);
	BOOL GetInAttract();
	void SetInAttract(BOOL);

// Operations
public:
	void GetStatus(BSTR* bstrDeviceName, BSTR* bstrCheckHealthText, long* lStatus);
	void ResetTimers(long nTimer);
	void SetSoldItemInfo(LPDISPATCH lpdispWeightInfo);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SMARTSCALE_H__918C5A9B_849D_4FE8_99ED_1E342359F7AA__INCLUDED_)
