// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "takeawaybeltcontrol.h"

/////////////////////////////////////////////////////////////////////////////
// CTakeawayBeltControl

IMPLEMENT_DYNCREATE(CTakeawayBeltControl, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CTakeawayBeltControl properties

/////////////////////////////////////////////////////////////////////////////
// CTakeawayBeltControl operations

BOOL CTakeawayBeltControl::Open(LPCTSTR ProfileName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		ProfileName);
	return result;
}

BOOL CTakeawayBeltControl::Close()
{
	BOOL result;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CTakeawayBeltControl::OnAppEvent(long Event)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Event);
}

void CTakeawayBeltControl::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
