#define PIDCLASS_START 10000
enum{
	PIDCLASS_BAGSCALE	=		PIDCLASS_START,
	PIDCLASS_WLDBSACONFIG		,
	PIDCLASS_FISCALPRTR			,
	PIDCLASS_MAX_CLASS			//IMPORTANT THIS MUST BE THE LAST Constant in list
};
