#if !defined(AFX_CEASWrapper_H__CA43E620_88EC_11D4_BBDA_00A0C9EDD466__INCLUDED_)
#define AFX_CEASWrapper_H__CA43E620_88EC_11D4_BBDA_00A0C9EDD466__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CEASWrapper wrapper class

#include "TOposEAS.h"

class CEASWrapper : public TOposEas<CGenericOposIF> 
   {
   public:  
      static TClassPtr<CGenericOposIF> CreateDevice( HKEY hKey, long nDeviceId )
         { return new CEASWrapper( nDeviceId ); }
      virtual void OnOposStatusEvent( long nStatus );  
      virtual CEASWrapper* GetEASDeactivator( void ) { return this; }
   protected:
      virtual bool IsInputDevice( void ) const { return true; }
public:
	BOOL Create( CWnd* pParentWnd, UINT nID );
   public:  // pure virtuals from CGenericOposIF
      virtual long GetDeviceClass( void ) const 
         { return DMCLASS_EASDEACTIVATOR; }
   // Attributes
   public:
   // Operations
   public:
   protected:
      CEASWrapper( long nDeviceId ) { m_nDeviceId = nDeviceId; } 
   };

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_EASDEACTIVATIONCTRL_H__CA43E620_88EC_11D4_BBDA_00A0C9EDD466__INCLUDED_)
