#if !defined(AFX_SECURITYMANAGER_H__8BE32B74_AE97_4871_AEFF_5B8FE14E17F0__INCLUDED_)
#define AFX_SECURITYMANAGER_H__8BE32B74_AE97_4871_AEFF_5B8FE14E17F0__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSecurityManager wrapper class

class CSecurityManager : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSecurityManager)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x55cfb38b, 0x6ce4, 0x465f, { 0x87, 0x16, 0xd5, 0xc0, 0xf2, 0x7c, 0xef, 0x8f } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetOutstandingInterventionList();
	void SetOutstandingInterventionList(LPCTSTR);
	CString GetDevices();
	void SetDevices(LPCTSTR);
	long GetOutstandingInterventionCount();
	void SetOutstandingInterventionCount(long);

// Operations
public:
	void SecurityUnadvise(long dwCookie);
	long SecurityAdvise(long lFlags);
	void ItemSold(long lCookie, LPCTSTR bstrParms);
	void ItemDetails(long lCookie, LPCTSTR bstrParms);
	void VoidItem(long lCookie, LPCTSTR bstrParms);
	void TransactionControl(long lCookie, LPCTSTR bstrParms);
	long AppControl(long lCookie, LPCTSTR bstrParms, BSTR* bstrOutParms);
	void OverrideException(long lCookie, LPCTSTR bstrParms);
	long SecurityMaintenance(long lCookie, LPCTSTR bstrParms);
	void SecurityControl(long lCookie, LPCTSTR bstrInParms, BSTR* bstrOutParms);
	long Initialize(long lCookie, LPCTSTR bstrInParms, BSTR* pbstrValues);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SECURITYMANAGER_H__8BE32B74_AE97_4871_AEFF_5B8FE14E17F0__INCLUDED_)
