//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSCOUIViews.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSCOUIViews.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount
        ///Due.
        /// </summary>
        public static string AmountDue {
            get {
                return ResourceManager.GetString("AmountDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Saved.
        /// </summary>
        public static string AmountSaved {
            get {
                return ResourceManager.GetString("AmountSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistance.
        /// </summary>
        public static string Assistance {
            get {
                return ResourceManager.GetString("Assistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistance is coming, please continue..
        /// </summary>
        public static string AssistanceComing {
            get {
                return ResourceManager.GetString("AssistanceComing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backspace.
        /// </summary>
        public static string Backspace {
            get {
                return ResourceManager.GetString("Backspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please bag this item..
        /// </summary>
        public static string BagItem {
            get {
                return ResourceManager.GetString("BagItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bag Item.
        /// </summary>
        public static string BagItemCart {
            get {
                return ResourceManager.GetString("BagItemCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please bag this item, or choose to skip..
        /// </summary>
        public static string BagItemOrSkip {
            get {
                return ResourceManager.GetString("BagItemOrSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call For Help?.
        /// </summary>
        public static string CallForHelp {
            get {
                return ResourceManager.GetString("CallForHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel All.
        /// </summary>
        public static string CancelAll {
            get {
                return ResourceManager.GetString("CancelAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Coupons.
        /// </summary>
        public static string CancelCoupons {
            get {
                return ResourceManager.GetString("CancelCoupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Payment.
        /// </summary>
        public static string CancelPayment {
            get {
                return ResourceManager.GetString("CancelPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Scan Coupons.
        /// </summary>
        public static string CantScanCoupon {
            get {
                return ResourceManager.GetString("CantScanCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Pinpad
        ///
        ///Press &quot;Cancel&quot; on pinpad to cancel payment..
        /// </summary>
        public static string CardProcessing {
            get {
                return ResourceManager.GetString("CardProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string CartPay {
            get {
                return ResourceManager.GetString("CartPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        public static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Cash Back Amount.
        /// </summary>
        public static string CashBack {
            get {
                return ResourceManager.GetString("CashBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change:.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Search.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lane
        ///Closed.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your zip code and touch &quot;OK&quot;.
        /// </summary>
        public static string CmDataEntryWithKeyBoard {
            get {
                return ResourceManager.GetString("CmDataEntryWithKeyBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to stop checking out and cancel your entire purchase?.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Empty Cart? The transaction will be cancelled..
        /// </summary>
        public static string ConfirmAbortMessage {
            get {
                return ResourceManager.GetString("ConfirmAbortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Amount.
        /// </summary>
        public static string ConfirmAmount {
            get {
                return ResourceManager.GetString("ConfirmAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is {0} correct?.
        /// </summary>
        public static string ConfirmQuantity {
            get {
                return ResourceManager.GetString("ConfirmQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove {0} from receipt?.
        /// </summary>
        public static string ConfirmVoid {
            get {
                return ResourceManager.GetString("ConfirmVoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An assistant will need to drop by and collect any removed items..
        /// </summary>
        public static string ConfirmVoidMessage {
            get {
                return ResourceManager.GetString("ConfirmVoidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to continue?.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set coupon aside for now. Deposit them at end of purchase..
        /// </summary>
        public static string CouponMessage {
            get {
                return ResourceManager.GetString("CouponMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Crate
        ///
        ///Purchase a full crate
        ///of &quot;{0}&quot;?.
        /// </summary>
        public static string CrateableItem {
            get {
                return ResourceManager.GetString("CrateableItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        public static string Debit {
            get {
                return ResourceManager.GetString("Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please deposit your depleted gift card in the coupon slot..
        /// </summary>
        public static string DepositCard {
            get {
                return ResourceManager.GetString("DepositCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Coupons.
        /// </summary>
        public static string DepositCoupon {
            get {
                return ResourceManager.GetString("DepositCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Gift Card.
        /// </summary>
        public static string DepositGiftCard {
            get {
                return ResourceManager.GetString("DepositGiftCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to SelfServ Checkout....
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due:.
        /// </summary>
        public static string Due {
            get {
                return ResourceManager.GetString("Due", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Cart.
        /// </summary>
        public static string EditCart {
            get {
                return ResourceManager.GetString("EditCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Amount.
        /// </summary>
        public static string EnterAmount {
            get {
                return ResourceManager.GetString("EnterAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter coupon&apos;s value in cents and touch &quot;OK&quot;.
        /// </summary>
        public static string EnterCouponValue {
            get {
                return ResourceManager.GetString("EnterCouponValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key in your ID..
        /// </summary>
        public static string EnterId {
            get {
                return ResourceManager.GetString("EnterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key in your password..
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Pin.
        /// </summary>
        public static string EnterPin {
            get {
                return ResourceManager.GetString("EnterPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many items do you have?.
        /// </summary>
        public static string EnterQuantity {
            get {
                return ResourceManager.GetString("EnterQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many do you have?.
        /// </summary>
        public static string EnterQuantityWithImageTitle {
            get {
                return ResourceManager.GetString("EnterQuantityWithImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place the item on the scale..
        /// </summary>
        public static string EnterWeight {
            get {
                return ResourceManager.GetString("EnterWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for shopping with us..
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish &amp; Add.
        /// </summary>
        public static string FinishAndAdd {
            get {
                return ResourceManager.GetString("FinishAndAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish &amp; Pay.
        /// </summary>
        public static string FinishPay {
            get {
                return ResourceManager.GetString("FinishPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift Card Balance.
        /// </summary>
        public static string GiftCard {
            get {
                return ResourceManager.GetString("GiftCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help is on the way.  Please continue..
        /// </summary>
        public static string HelpOnWay {
            get {
                return ResourceManager.GetString("HelpOnWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lane is offline and the system is attempting to reconnect..
        /// </summary>
        public static string HostOfflineMessage {
            get {
                return ResourceManager.GetString("HostOfflineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect operator number
        ///and password.
        ///Please try again..
        /// </summary>
        public static string IncorrectLogin {
            get {
                return ResourceManager.GetString("IncorrectLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert / Swipe card.
        /// </summary>
        public static string InsertCard {
            get {
                return ResourceManager.GetString("InsertCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Cash.
        /// </summary>
        public static string InsertCash {
            get {
                return ResourceManager.GetString("InsertCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Coupon.
        /// </summary>
        public static string InsertCoupon {
            get {
                return ResourceManager.GetString("InsertCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set item aside and continue 
        ///with your purchase..
        /// </summary>
        public static string InvalidBarcodeScan {
            get {
                return ResourceManager.GetString("InvalidBarcodeScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOI:.
        /// </summary>
        public static string ItemNumberAmount {
            get {
                return ResourceManager.GetString("ItemNumberAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Limit
        ///Exceeded.
        /// </summary>
        public static string ItemQuantityExceeded {
            get {
                return ResourceManager.GetString("ItemQuantityExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceeded 
        ///the quantity allowed 
        ///for this item. Set 
        ///item aside and 
        ///continue..
        /// </summary>
        public static string ItemQuantityExceededMessage {
            get {
                return ResourceManager.GetString("ItemQuantityExceededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items added to cart..
        /// </summary>
        public static string ItemsAddedFormat {
            get {
                return ResourceManager.GetString("ItemsAddedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lane Closed.
        /// </summary>
        public static string LaneClosedMessage {
            get {
                return ResourceManager.GetString("LaneClosedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your frequent shopper account has been activated..
        /// </summary>
        public static string LoyaltyMessage {
            get {
                return ResourceManager.GetString("LoyaltyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Cart.
        /// </summary>
        public static string MyCart {
            get {
                return ResourceManager.GetString("MyCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NCR Corp.
        /// </summary>
        public static string NCRCorp {
            get {
                return ResourceManager.GetString("NCRCorp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, keep..
        /// </summary>
        public static string NoKeep {
            get {
                return ResourceManager.GetString("NoKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, return to transaction..
        /// </summary>
        public static string NoReturn {
            get {
                return ResourceManager.GetString("NoReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Payment.
        /// </summary>
        public static string OtherPayment {
            get {
                return ResourceManager.GetString("OtherPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other payment methods.
        /// </summary>
        public static string OtherPaymentMethod {
            get {
                return ResourceManager.GetString("OtherPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own Bag.
        /// </summary>
        public static string OwnBag {
            get {
                return ResourceManager.GetString("OwnBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please place your bags on the scale..
        /// </summary>
        public static string OwnBagMessage {
            get {
                return ResourceManager.GetString("OwnBagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid:.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay the rest  another way.
        /// </summary>
        public static string PayAnotherWay {
            get {
                return ResourceManager.GetString("PayAnotherWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAY.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a payment option.
        /// </summary>
        public static string PaymentOption {
            get {
                return ResourceManager.GetString("PaymentOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points Earned.
        /// </summary>
        public static string PointsEarned {
            get {
                return ResourceManager.GetString("PointsEarned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Receipt.
        /// </summary>
        public static string PrintReceipt {
            get {
                return ResourceManager.GetString("PrintReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Proceed {
            get {
                return ResourceManager.GetString("Proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Picks.
        /// </summary>
        public static string QuickPick {
            get {
                return ResourceManager.GetString("QuickPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I removed item.
        /// </summary>
        public static string RemovedItem {
            get {
                return ResourceManager.GetString("RemovedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Item.
        /// </summary>
        public static string RemoveItem {
            get {
                return ResourceManager.GetString("RemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricted Item.
        /// </summary>
        public static string RestrictedItem {
            get {
                return ResourceManager.GetString("RestrictedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Sale.
        /// </summary>
        public static string ReturnToSale {
            get {
                return ResourceManager.GetString("ReturnToSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string ReturnToScan {
            get {
                return ResourceManager.GetString("ReturnToScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to NCR Self Serv Checkout!.
        /// </summary>
        public static string RewardGreeting {
            get {
                return ResourceManager.GetString("RewardGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan, search, or key in item code to start..
        /// </summary>
        public static string ScanAndBag {
            get {
                return ResourceManager.GetString("ScanAndBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Coupon.
        /// </summary>
        public static string ScanCoupon {
            get {
                return ResourceManager.GetString("ScanCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Gift Card.
        /// </summary>
        public static string ScanGiftCard {
            get {
                return ResourceManager.GetString("ScanGiftCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan next item..
        /// </summary>
        public static string ScanNextItem {
            get {
                return ResourceManager.GetString("ScanNextItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Voucher.
        /// </summary>
        public static string ScanVoucher {
            get {
                return ResourceManager.GetString("ScanVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results for &quot;{0}&quot;.
        /// </summary>
        public static string SearchResultsFor {
            get {
                return ResourceManager.GetString("SearchResultsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchString {
            get {
                return ResourceManager.GetString("SearchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Item Name or Code.
        /// </summary>
        public static string SearchWatermark {
            get {
                return ResourceManager.GetString("SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search or Key in Item.
        /// </summary>
        public static string SearckKeyInItem {
            get {
                return ResourceManager.GetString("SearckKeyInItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Cash Back Amount.
        /// </summary>
        public static string SelectCashBack {
            get {
                return ResourceManager.GetString("SelectCashBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Container.
        /// </summary>
        public static string SelectContainer {
            get {
                return ResourceManager.GetString("SelectContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Payment Type.
        /// </summary>
        public static string SelectPaymentType {
            get {
                return ResourceManager.GetString("SelectPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many plastic bags did you use?  Enter 0 if you didn&apos;t use any..
        /// </summary>
        public static string SellBags {
            get {
                return ResourceManager.GetString("SellBags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entire purchase cancelled.
        ///Set all items aside..
        /// </summary>
        public static string SetAllItemsAsideMessage {
            get {
                return ResourceManager.GetString("SetAllItemsAsideMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Needed.
        /// </summary>
        public static string SignNeeded {
            get {
                return ResourceManager.GetString("SignNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign signature pad..
        /// </summary>
        public static string SignSignature {
            get {
                return ResourceManager.GetString("SignSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Bagging.
        /// </summary>
        public static string SkipBagging {
            get {
                return ResourceManager.GetString("SkipBagging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        public static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Scanning.
        /// </summary>
        public static string StartScanning {
            get {
                return ResourceManager.GetString("StartScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Log In.
        /// </summary>
        public static string StoreLogin {
            get {
                return ResourceManager.GetString("StoreLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Your Returned Cash.
        /// </summary>
        public static string TakeCash {
            get {
                return ResourceManager.GetString("TakeCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Change.
        /// </summary>
        public static string TakeChange {
            get {
                return ResourceManager.GetString("TakeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Receipt.
        /// </summary>
        public static string TakeReceipt {
            get {
                return ResourceManager.GetString("TakeReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Restricted Item.
        /// </summary>
        public static string TimeRestrictedItem {
            get {
                return ResourceManager.GetString("TimeRestrictedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are unable to
        ///purchase this item at
        ///this time. Set item
        ///aside and continue..
        /// </summary>
        public static string TimeRestrictedItemMessage {
            get {
                return ResourceManager.GetString("TimeRestrictedItemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch cancel on pinpad to cancel payment..
        /// </summary>
        public static string TouchCancel {
            get {
                return ResourceManager.GetString("TouchCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return item to bag area..
        /// </summary>
        public static string UnexpectedDecreaseMessage {
            get {
                return ResourceManager.GetString("UnexpectedDecreaseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove item from bag area..
        /// </summary>
        public static string UnexpectedIncreaseMessage {
            get {
                return ResourceManager.GetString("UnexpectedIncreaseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Item.
        /// </summary>
        public static string UnknownItem {
            get {
                return ResourceManager.GetString("UnknownItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help is on the way.
        ///Set item aside and
        ///continue..
        /// </summary>
        public static string UnknownItemMessage {
            get {
                return ResourceManager.GetString("UnknownItemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item&apos;s price is unknown.
        ///Help is on the way.
        ///Set item aside and continue..
        /// </summary>
        public static string UnknownPriceMessage {
            get {
                return ResourceManager.GetString("UnknownPriceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m using my own bag.
        /// </summary>
        public static string UseOwnBag {
            get {
                return ResourceManager.GetString("UseOwnBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Pinpad.
        /// </summary>
        public static string UsePinpad {
            get {
                return ResourceManager.GetString("UsePinpad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendant will verify your bags..
        /// </summary>
        public static string VerifyBags {
            get {
                return ResourceManager.GetString("VerifyBags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have accidentally placed something other than a bag in the bagging area, please remove it now..
        /// </summary>
        public static string VerifyBagsMessage {
            get {
                return ResourceManager.GetString("VerifyBagsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void Approval.
        /// </summary>
        public static string VoidApproval {
            get {
                return ResourceManager.GetString("VoidApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for
        ///Attendant..
        /// </summary>
        public static string VoidApprovalMessage {
            get {
                return ResourceManager.GetString("VoidApprovalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan unwanted items, or tap
        ///&quot;Remove&quot; on the receipt..
        /// </summary>
        public static string VoidItem {
            get {
                return ResourceManager.GetString("VoidItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for store
        ///approval for other
        ///payment method..
        /// </summary>
        public static string WaitForApproval {
            get {
                return ResourceManager.GetString("WaitForApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WE:.
        /// </summary>
        public static string WeightExpected {
            get {
                return ResourceManager.GetString("WeightExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking item weight.
        ///
        ///Please wait....
        /// </summary>
        public static string WeightMismatch {
            get {
                return ResourceManager.GetString("WeightMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WO:.
        /// </summary>
        public static string WeightObserved {
            get {
                return ResourceManager.GetString("WeightObserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, empty cart and end transaction..
        /// </summary>
        public static string YesEmpty {
            get {
                return ResourceManager.GetString("YesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, remove..
        /// </summary>
        public static string YesRemove {
            get {
                return ResourceManager.GetString("YesRemove", resourceCulture);
            }
        }
    }
}
