// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "rcmgrwrapper.h"

/////////////////////////////////////////////////////////////////////////////
// CRemoteConsoleMgrWrapper

IMPLEMENT_DYNCREATE(CRemoteConsoleMgrWrapper, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CRemoteConsoleMgrWrapper properties

/////////////////////////////////////////////////////////////////////////////
// CRemoteConsoleMgrWrapper operations

long CRemoteConsoleMgrWrapper::Initialize(long pPSX)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		pPSX);
	return result;
}

long CRemoteConsoleMgrWrapper::Terminate()
{
	long result;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CRemoteConsoleMgrWrapper::CanApprove(LPCTSTR bstrInParms, long* pResult)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_PI4;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		bstrInParms, pResult);
	return result;
}

long CRemoteConsoleMgrWrapper::GetApprovalInfo(LPCTSTR bstrInParms, BSTR* pbstrOutParms)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_PBSTR;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		bstrInParms, pbstrOutParms);
	return result;
}

long CRemoteConsoleMgrWrapper::OnControl(LPCTSTR bstrInParms, BSTR* pbstrOutParms)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_PBSTR;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		bstrInParms, pbstrOutParms);
	return result;
}

long CRemoteConsoleMgrWrapper::OnEvent(LPCTSTR bstrInParms)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		bstrInParms);
	return result;
}

long CRemoteConsoleMgrWrapper::Get(LPCTSTR bstrInParms, BSTR* pbstrOutParms)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_PBSTR;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		bstrInParms, pbstrOutParms);
	return result;
}

long CRemoteConsoleMgrWrapper::Set(LPCTSTR bstrInParms)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		bstrInParms);
	return result;
}

long CRemoteConsoleMgrWrapper::OnApproval(LPCTSTR bstrParms)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		bstrParms);
	return result;
}

long CRemoteConsoleMgrWrapper::OnInputEvent(LPCTSTR bstrInParms)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		bstrInParms);
	return result;
}