/////////////////////////////////////////////////////////////////////////////////////////////////
//
// FILE:  SCUDEFS.H   
//
// SCOT CUSTOMER DEFINED CONSTANTS
//
//////////////////////////////////////////////////////////////////////////////////////////////////

#ifndef _SCUDEFS_	// SCOT CUSTOMER DEFINED CONSTANTS
#define _SCUDEFS_


const enum SCUD_BMPS
{
	SSF_BMP1 = SCUD_BASE+1,
	SSF_BMP2,
	SCUDBMPS_LAST
};

const enum SCUD_MSGS
{
// +RFQ 7477
	SSF_LTT_INVALID_LOGIN_CONFIG = SCUD_BASE+1,         //9000 + 1
    SSF_TXT_INVALID_LOGIN_CONFIG,                       //2
    SSF_NEEDASSIST_DATAENTRY,                           //3
	SSF_NEEDASSIST_TOPCAPTION,                          //4
	SSF_NEEDASSIST_BOTTOMCAPTION,                       //5
	SSF_NEEDASSIST_SUMMARYINSTRUCTIONS,                 //6
	SSF_TBTXT_PLEASE_TRY_AGAIN,                         //7
	SSF_TBTXT_INVALID_SIGNATURE,                        //8
	SSF_TBTXT_CANT_READ_CARD,                           //9
	SSF_TBTXT_FREQ_SHOPPER_ACTIVATED,                   //10
	SSF_TBLTTXT_FREQ_SHOPPER_ACTIVATED,                 //11
	SSF_LTT_INVALID_TRAINING_LOGIN_CONFIG,              //12
	SSF_TXT_INVALID_TRAINING_LOGIN_CONFIG,              //13
	SSF_LTT_DUPLICATE_TRAINING_LOGIN,                   //14
	SSF_TXT_DUPLICATE_TRAINING_LOGIN,                   //15
	SSF_TXT_COLLECTNEGATIVEMEDIA,						//16
	
	SSF_TXT_PLEASE_INSERT_TAP_SWIPE_CARD = SCUD_BASE+21, // 9021=Please insert, tap \nor Swipe the card
	SSF_TXT_PLEASE_INSERT_TAP_SWIPE_CARD2,				 // 9022=Please insert, tap \nor Swipe the card
	
	SSF_BTT_PRINTGIFTRECEIPT = SCUD_BASE+50,

    SSF_BTT_PRINTREBATERECEIPT = SCUD_BASE+53,          // 53 - POS18905
        
    SSF_BTT_DUPLICATERECEIPT = SCUD_BASE+57,
	SSF_TXT_VOIDATTEMPT_LINE1 = SCUD_BASE+72,
	SSF_TXT_VOIDATTEMPT_LINE2 = SCUD_BASE+73,
	SSF_TXT_VOIDATTEMPT_LINE3 = SCUD_BASE+74,

	SSF_TXT_GUEST_AGE = SCUD_BASE+104,
	SSF_TXT_GUEST_NODATENEEDED = SCUD_BASE+105,

    SSF_BTT_PRICE_INQUIRY = SCUD_BASE+120,              //9120
	SSF_TXT_MEPAVAILABLE = SCUD_BASE+131,		//CRD 269544

	SSF_BTT_NEWTRANSACTION = SCUD_BASE+132,				//132
	SSF_LTT_COMPLETETRX_FINISHPAY,						//133
	SSF_LTT_SELECTOPTION_BEGIN,							//134
	SSF_TXT_SCAN_RECEIPT,								//135
	SSF_LTT_RETRIEVING_RECEIPT,							//136
	SSF_TXT_RETRIEVING_RECEIPT_WAIT,					//137
	SSF_TXT_INVALID_RECEIPT,							//138
	SSF_TXT_TRX_RETRIEVAL,								//139
	SSF_BTT_BACKTO_SHOPPING,							//140
	SSF_TXT_SUPERVISOR_SCREEN = SCUD_BASE + 149,
	SSF_LTT_SUPERVISOR_SCREEN,
	SSF_TXT_SUPERVISOR_PWD_SCREEN,
	SSF_LTT_SUPERVISOR_PWD_SCREEN,
	SSF_LTT_SUPERVISOR_INVALID,
	SSF_LTT2_SUPERVISOR_INVALID,
	SSF_LTT_INSERT_PAYMENT = SCUD_BASE+157,
	SSF_MSG_THANKYOUFORSHOPPINGMEIJER = SCUD_BASE+160,
	SSF_MSG_TAKECHANGETIMEREXPIRED = SCUD_BASE+162,
	SSF_BTT_WIC_CARD = SCUD_BASE+167,
	SSF_MSG_WIC_CARD_PROCESSING,
	SSF_MSG_SCAN_WIC_ITEMS,	

    // EMPLID & Biometric leadthrus                    
    MSG_ENTERID_SCANIDORKEY = SCUD_BASE+187,        // 9187
    MSG_ENTERID_SCANIDONLY,                         // 9188
    MSG_ENTERPASSWORD_ORUSEBIOMETRIC,               // 9189
    SSF_LTT_INCORRECTLOGIN,                         // 9190=Incorrect Login
    SSF_MSG_EMPLIDPASSWORD_INVALID,                 // 9191=\nIncorrect Employee ID and password.\n\nPlease try again.
    SSF_MSG_BADGEPASSWORD_INVALID,                  // 9192=\nIncorrect Employee badge and password.\n\nPlease try again.
    SSF_MSG_EMPLIDBIOMET_INVALID,                   // 9193=\nIncorrect Employee ID and fingerpint.\n\nPlease try again.
    SSF_MSG_BADGEBIOMET_INVALID,                    // 9194=\nIncorrect Employee badge and fingerprint.\n\nPlease try again.
    
	RESERVED_FOR_LTT_PAY_CHECK_ON_LANE = SCUD_BASE + 220,		//9220 - Begin RFC 356020 
	RESERVED_FOR_MSG_INSERT_CHECK_ON_LANE,						//9221
	RESERVED_FOR_LTT_MICR_ERR_TITLE1,							//9222
	RESERVED_FOR_LTT_MICR_ERR_TITLE2,							//9223
	RESERVED_FOR_MSG_MICR_NO_DATA,								//9224
	RESERVED_FOR_MSG_MICR_TIMEOUT,								//9225
	RESERVED_FOR_MSG_MICR_UNEXPECTED,							//9226
	RESERVED_FOR_MSG_MICR_NO_HARDWARE,							//9227
	RESERVED_FOR_MSG_MICR_JAM,									//9228
	RESERVED_FOR_MSG_MICR_LINE_ERROR,							//9229
	RESERVED_FOR_MSG_MICR_NO_CHECK,								//9230
	RESERVED_FOR_MSG_MICR_BAD_CHECK,								//9231
	RESERVED_FOR_RA_CHECK_ON_LANE,								//9232
	RESERVED_FOR_MSG_CHECK_DEVICE_NOT_AVAILABLE,					//9233
    RESERVED_FOR_MSG_MICR_CHECK_JAM,								//9234
	RESERVED_FOR_MSG_MICR_GENERAL_FAILURE,						//9235
	RESERVED_FOR_MSG_MICR_TIMEOUT_TEXT,							//9236
	RESERVED_FOR_MSG_MICR_NOT_CONNECTED,							//9237 - End RFC 356020
    
    SSF_AGE_REQUIRED = 9247,                                     //9247

	SSF_TXT_MEPPROMPT = 9268,	//CRD 269544

    SSF_BTT_APPLYREBATECHECK        = 9293,                           // 9293 - POS18905
    SSF_BTT_APPLYREBATECHECK_YES    = 9294,                           // 9294 - POS18905
    SSF_BTT_REBATECHECK             = 9295,                           // 9295 - POS18905
    SSF_MSG_SUPERVISOR_REBATECHECK  = 9296,                           // 9296 - POS18905

    SSF_BTT_APPLYPROMOTIONALITEMS = 9298,           // POS19072: 9298=Apply Promotional Items
    SSF_LTT_APPLYPROMOTIONALITEMS = 9299,           // POS19072: 9299=Apply Promotional Items
    SSF_MSG_APPLYPROMOTIONALITEMS = 9300,           // POS19072: 9300=Are you finished entering your WIC eligible items?
    SSF_LTT_SCANPROMOTIONALITEMS  = 9301,           // POS19072: 9301=Scan Promotional Items
    SSF_MSG_NOTPROMOTIONALITEM    = 9302,           // POS19072: 9302=Item is not a promotional item and cannot be sold in this transaction. Set item aside.
    
   SSF_TXT_MOBILE_AUDIT = 9303,                          //9303   POS11024

   SSF_LTT_COUPON_ONCEANDDONE = 9317, 			// POS55714

   // POS31050 
   SSF_TXT_ENHANCEDAM_LOGOUT            = 9322,
   SSF_TXT_ENHANCEDAM_TOTALITEM         = 9323,
   SSF_TXT_ENHANCEDAM_MOBILE_ASSISTANCE = 9324,
   SSF_TXT_ENHANCEDAM_MOBILE_ASSISTANCE_LINE1 = 9325,
   SSF_TXT_ENHANCEDAM_MOBILE_ASSISTANCE_LINE2 = 9326,
   // e POS31050 

   //POS31051
   SSF_TXT_ENHANCEDAM_TOTALREMOVEDITEM = 9327,
   //e POS31051

   //POS31054 - mobile order lane light rrs
   SSF_TXT_ENHANCEDAM_MOBILE_RESUME = 9328,
   //e pos31054
    SSF_LTT_COINSTAR_BOTTLESLIP = 9329, 			// POS36319
    SSF_TXT_COINSTAR_BOTTLESLIP = 9330, 			// POS36319

    SSF_LTT_HIGHVALUE_PROMO = 9331,             // POS39475
    SSF_TXT_HIGHVALUE_PROMO = 9332,             // POS39475

    SSF_LTT_COUPONCHOICE_SELECTION = 9333,      // POS33020 Coupon Selection
    SSF_TXT_COUPONCHOICE_MPERKS    = 9334,      // POS33020 mPerks Digital Coupon
    SSF_BTT_COUPONCHOICE_MPERKS    = 9335,      // POS33020 Continue with mPerks
    SSF_BTT_COUPONCHOICE_MPERKS2   = 9336,      // POS33020 Paper Coupon Available for Future Use
    SSF_TXT_COUPONCHOICE_VENDOR    = 9337,      // POS33020 Manufacturer/Vendor Coupon
    SSF_BTT_COUPONCHOICE_VENDOR    = 9338,      // POS33020 Continue with Paper Coupon
    SSF_BTT_COUPONCHOICE_VENDOR2   = 9339,      // POS33020 mPerks Available for Future Use
    SSF_TXT_COUPONCHOICE_INSERTCOUPON = 9340,   // POS33020 Please Enter mPerks Or Insert Coupon

    SSF_TXT_FOODSTAMPS            = 9347,    //POS54860 Foodstamp  
    SSF_TXT_RAINCHECK_NOT_ALLOWED = 9348,   //POS57686 Please See Attendant For Raincheck.
    SSF_TXT_INSERT_SMARTCARD = 9364,   //POS138634
    SSF_TXT_REQUEST_SCANNER       = 9365, // POS181195
    SSF_TXT_SCANNER_ACTIVE        = 9366, // POS181195
    SSF_TXT_SCANNER_UNAVAILABLE   = 9367, // POS181195
	// start CRD126194
	SSF_TXT_BUTTON_HHSCAN_AVAIL		= 9426,
	SSF_TXT_BUTTON_HHSCAN_NOTAVAIL	= 9427,
	SSF_TXT_BUTTON_HHSCAN_RELEASE	= 9428,
	// end CRD126194
	SSF_TXT_VOIDITEM			= 9429,  //VSTS 131568
	
	SSF_TXT_PHONE_NOTIFICATION = 9430,
	SSF_TXT_SCANNER_DEACTIVATED = 9431,  //CRD149415
	
	//Start CRD 130212
	SSF_TXT_EAS_INTERVENTION = 9512,
	SSF_TXT_EAS_ITEM_DESC = 9513,
	SSF_TXT_EAS_ITEM_TAG = 9515,
	//End CRD 130212
	SSF_TXT_MOBILE_ASSISTANCE_INTERVENTION = 9516,	//CRD 223409
	SSF_TXT_MEIJERGO_SALE_NOTALLOWED_TITLE = 9527,
	SSF_TXT_MEIJERGO_SALE_NOTEALLWED_MESSAGE = 9528,
	SSF_TXT_ADD_MORE_IMPULSE_ITEMS_MESSAGE = 9530, //CRD 515498
	
	// Start CRD 526693
	SSF_TXT_APPLY_MEIJERCARD = 9540,
	SSF_TXT_MEIJERCARD_VERIFICATION = 9541,			
	SSF_TXT_MEIJERCARD_VERIFYTOLANE = 9542,
	// End CRD 526693
	// Start CRD 554916
	SSF_TXT_ACCOUNT_LOOKUP_FAILED_INTERVENTION = 9545,
	// End CRD 554916
	SSF_LTT_SOMETHINGWENTWRONG = 9546,					// CRD 584194
	SSF_TXT_SCANTRYAGAIN = 9547,						// CRD 584194
	SSF_TXT_GET_ACCOUNT_DETAILS_FAILED_INTERVENTION = 9548, // CRD 557225
	
	//Please add new entries above this line
	// -RFQ 7477
	SCUDMSGS_LAST
};

// START TAR : 242837
const enum SSF_BEST // SCOT customer or SSF defined base entry states
{
	SSF_BES_SSFSTATE1 = BEST_BASE+1,
	SSF_BES_LAST
};
// END TAR : 242837

//Start CRD515496
const enum SSF_WAV
{
	SSF_WAV_SS90_IMPULSE_ITEMS = 100
};

#endif //  _SCUDEFS_	// SCOT CUSTOMER DEFINED CONSTANTS