#include "StdAfx.h"
#include "ACS.h"

LPCTSTR ACS::OPT_APPMODEL		= _T("ApplicationModel");
LPCTSTR ACS::OPT_APPMODEL_DEF	= _T("C:\\scot\\config\\ApplicationModel.xml");
LPCTSTR ACS::OPT_FINALAPPMODEL	= _T("FinalMergedApplicationModel");
LPCTSTR ACS::OPT_FINALAPPMODEL_DEF = _T("C:\\scot\\config\\FinalMergedApplicationModel.xml");
LPCTSTR ACS::OPT_ACSIODLL		= _T("ACSIODLL");
LPCTSTR ACS::OPT_ACSIODLL_DEF	= _T("C:\\ACS\\bin\\ACSIOClient.dll");
LPCTSTR ACS::OPT_ACSEXFUNCSDLL  = _T("ACSEXFUNCSDLL");
LPCTSTR ACS::OPT_ACSEXFUNCSDLL_DEF = _T("C:\\ACS\\bin\\ACSExposedFunctions.dll");
LPCTSTR ACS::OPT_OPERATOR = _T("Operator");
LPCTSTR ACS::OPT_PASSWORD = _T("Password");
LPCTSTR ACS::OPT_ACSIO_QUEUE_ENTRIES = _T("ACSIOQueueEntries");
LPCTSTR ACS::OPT_ACSIO_QUEUE_ENTRIES_DEF = _T("50");
LPCTSTR ACS::OPT_OPOS_LISTENTODEVICES = _T("ListenToDevices");
LPCTSTR ACS::OPT_OPOS_LISTENTODEVICES_DEF = _T("54,40,67,30");
LPCTSTR ACS::OPT_APPLICATIONNAME = _T("ApplicationName");
LPCTSTR ACS::OPT_APPLICATIONNAME_DEF = _T("salesw2k.exe");
LPCTSTR ACS::OPT_AUXMSG_ISEQ = _T("AuxMsgInputSequence");
LPCTSTR ACS::OPT_AUXMSG_ISEQ_DEF = _T("FL_NOTIFY_ENTERED");
LPCTSTR ACS::OPT_AUXMSG_PROP = _T("AuxMsgProperty");
LPCTSTR ACS::OPT_AUXMSG_PROP_DEF = _T("PropFLNotifyData");
LPCTSTR ACS::OPT_AUXMSG_ID_PROP = _T("AuxMsgIdProperty");
LPCTSTR ACS::OPT_AUXMSG_ID_PROP_DEF = _T("PropFLNotifyId");