

	typedef enum TelnetXPropsDispids
	{
		DISPID_host=1,
		DISPID_blocking,
		DISPID_debugmode,
		DISPID_blockingmode,
		DISPID_port,
		DISPID_lasterror,
		DISPID_lasterrorstring,
		DISPID_libraryname,
		DISPID_state,
		DISPID_statestring,
		DISPID_timeout,
		DISPID_version,
		DISPID_localhost,
		DISPID_localip,
		DISPID_terminalname,
		DISPID_terminaltype,
		DISPID_firewallhost,
		DISPID_firewallport,
		DISPID_firewalllogonname,
		DISPID_firewallpassword,
		DISPID_firewalltype,
		DISPID_autologon,
		DISPID_logonname,
		DISPID_logonpassword,
		DISPID_prompt,
		DISPID_logoncommand,
		DISPID_protocol,
		DISPID_encryption,
		DISPID_licensekey,
		DISPID_connect,
		DISPID_disconnect,
		DISPID_receive,
		DISPID_send,
		DISPID_notificationobject
	} TelnetXPropsDispids;
