#pragma once
// $Header: /Integration_Customer/Meijer/CURRENT_DEV/Platform-Patch/Remote Console Manager/src/state-machine/SMError.h 1     6/20/08 1:13p Sa250050 $
/*
 * @(#)SMError.h      $Revision: 1 $  $Date: 6/20/08 1:13p $
 *
 * Copyright 2004, NCR Corporation.
 *
 * All rights reserved.
 *
 * This software is the confidential and proprietary information
 * of NCR Corporation. ("Confidential Information").  You
 * shall not disclose such Confidential Information and shall use
 * it only in accordance with the terms of the license agreement
 * you entered into with msi.
 */

#include "xerror.h"
#include "statem.h"
#include "xmlerror.h"

// Provides the definitions for all HRESULT values returned by the Security component
// both internally and externally.
#define SM_ERROR_BASE                 0xC0040001L

#define STATEM_NO_RULES_DEFINED               _HRESULT_TYPEDEF_(SM_ERROR_BASE)
#define STATEM_INVALID_ACTION_ID              _HRESULT_TYPEDEF_((SM_ERROR_BASE+1))
#define STATEM_INVALID_MSG_ID                 _HRESULT_TYPEDEF_((SM_ERROR_BASE+2))
#define STATEM_INVALID_STATE_ID               _HRESULT_TYPEDEF_((SM_ERROR_BASE+3))
#define STATEM_UNDEFINED_ACTION_ID            _HRESULT_TYPEDEF_((SM_ERROR_BASE+4))
#define STATEM_UNDEFINED_MSG_ID               _HRESULT_TYPEDEF_((SM_ERROR_BASE+5))
#define STATEM_UNDEFINED_STATE_ID             _HRESULT_TYPEDEF_((SM_ERROR_BASE+6))
#define STATEM_OBJECT_ALREADY_DEFINED         _HRESULT_TYPEDEF_((SM_ERROR_BASE+7))
#define STATEM_DUPLICATE_ACTION_ID            _HRESULT_TYPEDEF_((SM_ERROR_BASE+8))
#define STATEM_DUPLICATE_MSG_ID               _HRESULT_TYPEDEF_((SM_ERROR_BASE+9))
#define STATEM_DUPLICATE_STATE_ID             _HRESULT_TYPEDEF_((SM_ERROR_BASE+10))
#define STATEM_DUPLICATE_VARIABLE_ID          _HRESULT_TYPEDEF_((SM_ERROR_BASE+11))
#define STATEM_DUPLICATE_INITIAL_STATE        _HRESULT_TYPEDEF_((SM_ERROR_BASE+12))
#define STATEM_UNDEFINED_VARIABLE             _HRESULT_TYPEDEF_((SM_ERROR_BASE+13))
#define STATEM_INVALID_VARIABLE_ID            _HRESULT_TYPEDEF_((SM_ERROR_BASE+14))
#define STATEM_UNDEFINED_VARIABLE_ID          _HRESULT_TYPEDEF_((SM_ERROR_BASE+15))
#define STATEM_UNDEFINED_INTERNAL_ACTION      _HRESULT_TYPEDEF_((SM_ERROR_BASE+16))
#define STATEM_UNDEFINED_OPERATION            _HRESULT_TYPEDEF_((SM_ERROR_BASE+17))
#define STATEM_DUPLICATE_TIMER_ID             _HRESULT_TYPEDEF_((SM_ERROR_BASE+18))
#define STATEM_DUPLICATE_CONSTANT_ID          _HRESULT_TYPEDEF_((SM_ERROR_BASE+19))
#define STATEM_UNDEFINED_TIMER_ID             _HRESULT_TYPEDEF_((SM_ERROR_BASE+20))
#define STATEM_UNDEFINED_CONSTANT_ID          _HRESULT_TYPEDEF_((SM_ERROR_BASE+21))
#define STATEM_DUPLICATE_GLOBAL_STATE         _HRESULT_TYPEDEF_((SM_ERROR_BASE+22))
#define STATEM_GLOBAL_STATE_NAME_NOT_ALLOWED  _HRESULT_TYPEDEF_((SM_ERROR_BASE+23))
#define STATEM_INVALID_CONSTANT_ID            _HRESULT_TYPEDEF_((SM_ERROR_BASE+24))
#define STATEM_INVALID_TIMER_ID               _HRESULT_TYPEDEF_((SM_ERROR_BASE+25))
#define STATEM_UNDEFINED_TIMER                _HRESULT_TYPEDEF_((SM_ERROR_BASE+26))
#define STATEM_UNDEFINED_CONSTANT             _HRESULT_TYPEDEF_((SM_ERROR_BASE+27))
#define STATEM_TIMEOUT_ALREADY_IN_PROGRESS    _HRESULT_TYPEDEF_((SM_ERROR_BASE+28))
#define STATEM_UNABLE_TO_START_TIMER          _HRESULT_TYPEDEF_((SM_ERROR_BASE+29))
#define STATEM_TIMEOUT_NOT_IN_PROGRESS        _HRESULT_TYPEDEF_((SM_ERROR_BASE+30))
#define STATEM_UNABLE_TO_STOP_TIMER           _HRESULT_TYPEDEF_((SM_ERROR_BASE+31))
#define STATEM_MISSING_TIMER_NAME             _HRESULT_TYPEDEF_((SM_ERROR_BASE+32))
#define STATEM_MISSING_TIMEOUT_VALUE          _HRESULT_TYPEDEF_((SM_ERROR_BASE+33))
#define STATEM_INVALID_TIMEOUT_VALUE          _HRESULT_TYPEDEF_((SM_ERROR_BASE+34))
#define STATEM_MISSING_VARIABLE_NAME          _HRESULT_TYPEDEF_((SM_ERROR_BASE+35))
#define STATEM_DUPLICATE_LIBRARY_NAME         _HRESULT_TYPEDEF_((SM_ERROR_BASE+36))
#define STATEM_MISSING_EXPRESSION             _HRESULT_TYPEDEF_((SM_ERROR_BASE+37))
#define STATEM_INVALID_EXPRESSION_ID          _HRESULT_TYPEDEF_((SM_ERROR_BASE+38))
#define STATEM_UNDEFINED_EXPRESSION_ID        _HRESULT_TYPEDEF_((SM_ERROR_BASE+39))
#define STATEM_MISSING_RC                     _HRESULT_TYPEDEF_((SM_ERROR_BASE+40))
#define STATEM_MULTIPLE_ACTIONS_DEFINED       _HRESULT_TYPEDEF_((SM_ERROR_BASE+41))
#define STATEM_MISSING_PARAMETER              _HRESULT_TYPEDEF_((SM_ERROR_BASE+42))
#define STATEM_INVALID_PARAMETER              _HRESULT_TYPEDEF_((SM_ERROR_BASE+43))
#define STATEM_MISSING_INCLUDE_NAME_ATTR      _HRESULT_TYPEDEF_((SM_ERROR_BASE+44))
#define STATEM_INVALID_UNKNOWN_ERROR_SM       _HRESULT_TYPEDEF_((SM_ERROR_BASE+45))
#define STATEM_NO_INITIAL_STATE               _HRESULT_TYPEDEF_((SM_ERROR_BASE+46))
#define STATEM_INVALID_IDENTIFIER             _HRESULT_TYPEDEF_((SM_ERROR_BASE+47))
#define STATEM_INVALID_TIMER_INTERVAL_ZERO    _HRESULT_TYPEDEF_((SM_ERROR_BASE+48))
#define STATEM_UNDEFINED_TAG                  _HRESULT_TYPEDEF_((SM_ERROR_BASE+49))
#define STATEM_NO_KEY_MAPPING                 _HRESULT_TYPEDEF_((SM_ERROR_BASE+50))
#define STATEM_MSG_CREATION_FAILED            _HRESULT_TYPEDEF_((SM_ERROR_BASE+51))
#define STATEM_UNDEFINED_MSG_NAME             _HRESULT_TYPEDEF_((SM_ERROR_BASE+52))
#define STATEM_UNDEFINED_STATETABLE_ID        _HRESULT_TYPEDEF_((SM_ERROR_BASE+53))
#define STATEM_DUPLICATE_STATETABLE_ID        _HRESULT_TYPEDEF_((SM_ERROR_BASE+54))
#define STATEM_INTERNAL_ERROR                 _HRESULT_TYPEDEF_((SM_ERROR_BASE+55))
#define STATEM_UNDEFINED_LOOKUPTABLE_ID       _HRESULT_TYPEDEF_((SM_ERROR_BASE+56))
#define STATEM_DUPLICATE_LOOKUPTABLE_ID       _HRESULT_TYPEDEF_((SM_ERROR_BASE+57))
#define STATEM_INVALID_LOOKUPTABLE_TYPE       _HRESULT_TYPEDEF_((SM_ERROR_BASE+58))
#define STATEM_INVALID_EXPRESSION_ACTION      _HRESULT_TYPEDEF_((SM_ERROR_BASE+59))
#define STATEM_INVALID_EXPRESSION_ACTION_PLIST  _HRESULT_TYPEDEF_((SM_ERROR_BASE+60))
#define STATEM_DM_OBJECT_ALREADY_REGISTERED   _HRESULT_TYPEDEF_((SM_ERROR_BASE+61))
#define STATEM_DM_OBJECT_NOT_REGISTERED       _HRESULT_TYPEDEF_((SM_ERROR_BASE+62))
#define STATEM_DM_PROPERTY_ALREADY_REGISTERED _HRESULT_TYPEDEF_((SM_ERROR_BASE+63))
#define STATEM_DM_PROPERTY_NOT_REGISTERED     _HRESULT_TYPEDEF_((SM_ERROR_BASE+64))

// DO NOT use the following defines.  They have been replaced by the equivalent
// STATEM_ defines
#define SECURITY_NO_RULES_DEFINED               STATEM_NO_RULES_DEFINED               
#define SECURITY_INVALID_ACTION_ID              STATEM_INVALID_ACTION_ID              
#define SECURITY_INVALID_MSG_ID                 STATEM_INVALID_MSG_ID                 
#define SECURITY_INVALID_STATE_ID               STATEM_INVALID_STATE_ID               
#define SECURITY_UNDEFINED_ACTION_ID            STATEM_UNDEFINED_ACTION_ID            
#define SECURITY_UNDEFINED_MSG_ID               STATEM_UNDEFINED_MSG_ID               
#define SECURITY_UNDEFINED_STATE_ID             STATEM_UNDEFINED_STATE_ID             
#define SECURITY_OBJECT_ALREADY_DEFINED         STATEM_OBJECT_ALREADY_DEFINED         
#define SECURITY_DUPLICATE_ACTION_ID            STATEM_DUPLICATE_ACTION_ID            
#define SECURITY_DUPLICATE_MSG_ID               STATEM_DUPLICATE_MSG_ID               
#define SECURITY_DUPLICATE_STATE_ID             STATEM_DUPLICATE_STATE_ID             
#define SECURITY_DUPLICATE_VARIABLE_ID          STATEM_DUPLICATE_VARIABLE_ID          
#define SECURITY_DUPLICATE_INITIAL_STATE        STATEM_DUPLICATE_INITIAL_STATE        
#define SECURITY_UNDEFINED_VARIABLE             STATEM_UNDEFINED_VARIABLE             
#define SECURITY_INVALID_VARIABLE_ID            STATEM_INVALID_VARIABLE_ID            
#define SECURITY_UNDEFINED_VARIABLE_ID          STATEM_UNDEFINED_VARIABLE_ID          
#define SECURITY_UNDEFINED_INTERNAL_ACTION      STATEM_UNDEFINED_INTERNAL_ACTION      
#define SECURITY_UNDEFINED_OPERATION            STATEM_UNDEFINED_OPERATION            
#define SECURITY_DUPLICATE_TIMER_ID             STATEM_DUPLICATE_TIMER_ID             
#define SECURITY_DUPLICATE_CONSTANT_ID          STATEM_DUPLICATE_CONSTANT_ID          
#define SECURITY_UNDEFINED_TIMER_ID             STATEM_UNDEFINED_TIMER_ID             
#define SECURITY_UNDEFINED_CONSTANT_ID          STATEM_UNDEFINED_CONSTANT_ID          
#define SECURITY_DUPLICATE_GLOBAL_STATE         STATEM_DUPLICATE_GLOBAL_STATE         
#define SECURITY_GLOBAL_STATE_NAME_NOT_ALLOWED  STATEM_GLOBAL_STATE_NAME_NOT_ALLOWED  
#define SECURITY_INVALID_CONSTANT_ID            STATEM_INVALID_CONSTANT_ID            
#define SECURITY_INVALID_TIMER_ID               STATEM_INVALID_TIMER_ID               
#define SECURITY_UNDEFINED_TIMER                STATEM_UNDEFINED_TIMER                
#define SECURITY_UNDEFINED_CONSTANT             STATEM_UNDEFINED_CONSTANT             
#define SECURITY_TIMEOUT_ALREADY_IN_PROGRESS    STATEM_TIMEOUT_ALREADY_IN_PROGRESS    
#define SECURITY_UNABLE_TO_START_TIMER          STATEM_UNABLE_TO_START_TIMER          
#define SECURITY_TIMEOUT_NOT_IN_PROGRESS        STATEM_TIMEOUT_NOT_IN_PROGRESS        
#define SECURITY_UNABLE_TO_STOP_TIMER           STATEM_UNABLE_TO_STOP_TIMER           
#define SECURITY_MISSING_TIMER_NAME             STATEM_MISSING_TIMER_NAME             
#define SECURITY_MISSING_TIMEOUT_VALUE          STATEM_MISSING_TIMEOUT_VALUE          
#define SECURITY_INVALID_TIMEOUT_VALUE          STATEM_INVALID_TIMEOUT_VALUE          
#define SECURITY_MISSING_VARIABLE_NAME          STATEM_MISSING_VARIABLE_NAME          
#define SECURITY_DUPLICATE_LIBRARY_NAME         STATEM_DUPLICATE_LIBRARY_NAME         
#define SECURITY_MISSING_EXPRESSION             STATEM_MISSING_EXPRESSION             
#define SECURITY_INVALID_EXPRESSION_ID          STATEM_INVALID_EXPRESSION_ID          
#define SECURITY_UNDEFINED_EXPRESSION_ID        STATEM_UNDEFINED_EXPRESSION_ID        
#define SECURITY_MISSING_RC                     STATEM_MISSING_RC                     
#define SECURITY_MULTIPLE_ACTIONS_DEFINED       STATEM_MULTIPLE_ACTIONS_DEFINED       
#define SECURITY_MISSING_PARAMETER              STATEM_MISSING_PARAMETER              
#define SECURITY_INVALID_PARAMETER              STATEM_INVALID_PARAMETER              
#define SECURITY_MISSING_INCLUDE_NAME_ATTR		STATEM_MISSING_INCLUDE_NAME_ATTR		
#define SECURITY_INVALID_UNKNOWN_ERROR_SM       STATEM_INVALID_UNKNOWN_ERROR_SM       
#define SECURITY_NO_INITIAL_STATE               STATEM_NO_INITIAL_STATE               
#define SECURITY_INVALID_IDENTIFIER             STATEM_INVALID_IDENTIFIER             
#define SECURITY_INVALID_TIMER_INTERVAL_ZERO    STATEM_INVALID_TIMER_INTERVAL_ZERO    
#define SECURITY_UNDEFINED_TAG                  STATEM_UNDEFINED_TAG                  


#define ITHROWSMERROR(id)\
    {\
        CSMErrorInfo error(id, _T(""));\
    	ITHROWSMERRORI(id, error)\
    }


#define ITHROWSMERRORTEXT(id, text)\
    {\
        CSMErrorInfo error(id, text);\
    	ITHROWSMERRORI(id, error)\
    }

#define ITHROWSMERRORI(id, info)\
    {\
    	CSMError exc(info.text(), id);\
        exc.setSeverity(IException::unrecoverable);\
     	exc.addLocation(IEXCEPTION_LOCATION());\
        exc.setErrorInfo(&info);\
	    throw(exc);\
    }

#pragma warning( push )
#pragma warning( disable : 4251 )

class STATEM_API CSMErrorInfo
    : public CXMLErrorInfo
{
    public:
        /*------------------------------- Constructors -------------------------------*/
          CSMErrorInfo ( HRESULT, int nLine=-1, int nCol=-1, const _TCHAR *pszFile=NULL, const _TCHAR *pszType=NULL );
          CSMErrorInfo ( HRESULT, const StringType &sText = _T("") );

        virtual
         ~CSMErrorInfo ( );

    protected:

        CSMErrorInfo (  );

	    const _TCHAR *lookupError(HRESULT);

    private:
        CSMErrorInfo ( const CSMErrorInfo& errorInformation );

        CSMErrorInfo
         &operator= ( const CSMErrorInfo& errorInformation );
}; // CSMErrorInfo


IEXCLASSDECLARE_API(CSMError,IException,STATEM_API);

#pragma warning( pop )
