// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "dbmgrclient.h"

/////////////////////////////////////////////////////////////////////////////
// CClientDBMgr

IMPLEMENT_DYNCREATE(CClientDBMgr, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CClientDBMgr properties

/////////////////////////////////////////////////////////////////////////////
// CClientDBMgr operations

long CClientDBMgr::StartItemLookup(LPDISPATCH pWTInfoObj)
{
	long result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		pWTInfoObj);
	return result;
}

long CClientDBMgr::LastChanceLookup(LPDISPATCH pWTInfoObj)
{
	long result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		pWTInfoObj);
	return result;
}

long CClientDBMgr::GetDeptException(LPCTSTR DeptID, LPDISPATCH pWTInfoObj)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_DISPATCH;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		DeptID, pWTInfoObj);
	return result;
}

long CClientDBMgr::SetUp()
{
	long result;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CClientDBMgr::GetStatus()
{
	long result;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CClientDBMgr::UpdateException(LPDISPATCH pWTInfoObj)
{
	long result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		pWTInfoObj);
	return result;
}

long CClientDBMgr::UpdateWLDB(LPDISPATCH pWTInfoObj)
{
	long result;
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		pWTInfoObj);
	return result;
}
long CClientDBMgr::TESTStartItemLookup(LPCTSTR csUPC)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		csUPC);
	return result;
}

long CClientDBMgr::TESTLastChanceLookup(LPCTSTR csUPC)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		csUPC);
	return result;
}
long CClientDBMgr::QuerySMMTol(LPCTSTR csUPC, long lDept, long lTolType, long lPPWU)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		csUPC, lDept, lTolType, lPPWU);
	return result;
}

long CClientDBMgr::QuerySMMWLDBwt(LPCTSTR csUPC, long lDept, LPCTSTR csDesc, long lPrice, long lSpecialItem, long lPPWU)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_BSTR VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		csUPC, lDept, csDesc, lPrice, lSpecialItem, lPPWU);
	return result;
}

long CClientDBMgr::UpdateSMMTol(long lAction, LPCTSTR csUPC, long lDept, long lTolType, long lWtExp, long lWtSubCk, long lWtTol, long lPPWU)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		lAction, csUPC, lDept, lTolType, lWtExp, lWtSubCk, lWtTol, lPPWU);
	return result;
}

long CClientDBMgr::UpdateSMMWLDBwt(long lAction, LPCTSTR csUPC, long lDept, long lBSwt, long lAppr, long lTally, long lDate, long lInitWt, long lPPWU)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		lAction, csUPC, lDept, lBSwt, lAppr, lTally, lDate, lInitWt, lPPWU);
	return result;
}

void CClientDBMgr::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
