// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "scotsignature.h"

/////////////////////////////////////////////////////////////////////////////
// CSCOTSignature

IMPLEMENT_DYNCREATE(CSCOTSignature, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CSCOTSignature properties

OLE_COLOR CSCOTSignature::GetBackColor()
{
	OLE_COLOR result;
	GetProperty(DISPID_BACKCOLOR, VT_I4, (void*)&result);
	return result;
}

void CSCOTSignature::SetBackColor(OLE_COLOR propVal)
{
	SetProperty(DISPID_BACKCOLOR, VT_I4, propVal);
}

short CSCOTSignature::GetBorderStyle()
{
	short result;
	GetProperty(DISPID_BORDERSTYLE, VT_I2, (void*)&result);
	return result;
}

void CSCOTSignature::SetBorderStyle(short propVal)
{
	SetProperty(DISPID_BORDERSTYLE, VT_I2, propVal);
}

short CSCOTSignature::GetXExtent()
{
	short result;
	GetProperty(0x1, VT_I2, (void*)&result);
	return result;
}

void CSCOTSignature::SetXExtent(short propVal)
{
	SetProperty(0x1, VT_I2, propVal);
}

short CSCOTSignature::GetYExtent()
{
	short result;
	GetProperty(0x2, VT_I2, (void*)&result);
	return result;
}

void CSCOTSignature::SetYExtent(short propVal)
{
	SetProperty(0x2, VT_I2, propVal);
}

BOOL CSCOTSignature::GetAutoExtent()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CSCOTSignature::SetAutoExtent(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

BOOL CSCOTSignature::GetYAxisFlipped()
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CSCOTSignature::SetYAxisFlipped(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CSCOTSignature operations

BOOL CSCOTSignature::DrawSignature(BSTR* pRawData)
{
	BOOL result;
	static BYTE parms[] =
		VTS_PBSTR;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		pRawData);
	return result;
}

BOOL CSCOTSignature::DrawSignatureFromPointArray(long lTotalPoints, BSTR* pRawData)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4 VTS_PBSTR;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		lTotalPoints, pRawData);
	return result;
}

void CSCOTSignature::ClearSigWindow()
{
	InvokeHelper(0x7, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CSCOTSignature::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
