
#if !defined(AFX_FLREPORTINGERRORS_H__B0FB529A_B74E_4643_B7BA_C915E9A1EFC5__INCLUDED_)
#define AFX_FLREPORTINGERRORS_H__B0FB529A_B74E_4643_B7BA_C915E9A1EFC5__INCLUDED_

#define FLRPT_OK                0
#define FLRPTERROR_CANTCREATE   1
#define FLRPTERROR_CANTLOAD     2
#define FLRPTERROR_COMEXCEPTION 3
#define FLRPTERR_EXCEPTION      4
#define FLRPT_NOTOPENED         5
#define FLRPT_NOTFOUND          6
#define FLRPT_CANTDELETE        7
#define FLRPT_INVALID_FILE      8
#define FLRPT_CANTMOVE          9
#define FLRPT_EOF               10
#define FLRPT_INVALIDPARM       11
#define FLRPTERR_IMPORTERROR    12
#endif