#if !defined(AFX_EASDeactivator_H__CA43E620_88EC_11D4_BBDA_00A0C9EDD466__INCLUDED_)
#define AFX_EASDeactivator_H__CA43E620_88EC_11D4_BBDA_00A0C9EDD466__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// EASDeactivator wrapper class
#include "OposControl.h"

class EASDeactivator : public COposControl
{
protected:
	DECLARE_DYNCREATE(EASDeactivator)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x3c0934, 0x344d, 0x4fe7, { 0xb5, 0x51, 0xa0, 0xee, 0x15, 0xf3, 0x62, 0x23 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	long GetBinaryConversion();
	void SetBinaryConversion(long);
	long GetCapPowerReporting();
	void SetCapPowerReporting(long);
	CString GetCheckHealthText();
	void SetCheckHealthText(LPCTSTR);
	BOOL GetClaimed();
	void SetClaimed(BOOL);
	BOOL GetDeviceEnabled();
	void SetDeviceEnabled(BOOL);
	BOOL GetFreezeEvents();
	void SetFreezeEvents(BOOL);
	long GetPowerNotify();
	void SetPowerNotify(long);
	long GetPowerState();
	void SetPowerState(long);
	long GetResultCode();
	void SetResultCode(long);
	long GetResultCodeExtended();
	void SetResultCodeExtended(long);
	long GetState();
	void SetState(long);
	CString GetControlObjectDescription();
	void SetControlObjectDescription(LPCTSTR);
	long GetControlObjectVersion();
	void SetControlObjectVersion(long);
	CString GetServiceObjectDescription();
	void SetServiceObjectDescription(LPCTSTR);
	long GetServiceObjectVersion();
	void SetServiceObjectVersion(long);
	CString GetDeviceName();
	void SetDeviceName(LPCTSTR);
	CString GetDeviceDescription();
	void SetDeviceDescription(LPCTSTR);
	BOOL GetCapDetectTagDeactivate();
	void SetCapDetectTagDeactivate(BOOL);
	long GetTagDeactivateMode();
	void SetTagDeactivateMode(long);
	long GetTimeout();
	void SetTimeout(long);

// Operations
public:
	long Open(LPCTSTR sProfile);
	long Close();
	long Claim(long lTimeout);
	long Release();
	long CheckHealth(long lLevel);
	long DirectIO(long lCommand, long* plData, BSTR* psData);
	void SOStatusUpdate(long lStatus);
	void SODirectIO(long lEventNumber, long* plData, BSTR* psData);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_EASDEACTIVATIONCTRL_H__CA43E620_88EC_11D4_BBDA_00A0C9EDD466__INCLUDED_)
