#if !defined(AFX_SCOTSIGNATURE_H__2AC2B013_D031_11D3_BBAD_00A0C9EDD523__INCLUDED_)
#define AFX_SCOTSIGNATURE_H__2AC2B013_D031_11D3_BBAD_00A0C9EDD523__INCLUDED_

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSCOTSignature wrapper class

class CSCOTSignature : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSCOTSignature)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xbbebf3e7, 0x643a, 0x11d2, { 0x91, 0x31, 0x0, 0x60, 0x97, 0x65, 0x85, 0x5d } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	short GetBorderStyle();
	void SetBorderStyle(short);
	short GetXExtent();
	void SetXExtent(short);
	short GetYExtent();
	void SetYExtent(short);
	BOOL GetAutoExtent();
	void SetAutoExtent(BOOL);
	BOOL GetYAxisFlipped();
	void SetYAxisFlipped(BOOL);

// Operations
public:
	BOOL DrawSignature(BSTR* pRawData);
	BOOL DrawSignatureFromPointArray(long lTotalPoints, BSTR* pRawData);
	void ClearSigWindow();
	void AboutBox();
};

#endif
