//////////////////////////////////////////////////////////////////////////////////////////////////
//
// FILE:  SCOTAPPDlg.h
//
// TITLE: SCOTAPP stands for SCOT IBM SMKT version
//
//
// Note: Most of this file was generated by the MFC App Wizard
// Changes for SCOT are noted.
// This module shows all store mode screens
//
//
//
//////////////////////////////////////////////////////////////////////////////////////////////////
//
// CHANGES: Start
//  DcL-021298 integrating the Security Agent features
//  DcL-051398 Using Standard procedures for Dialogs
// CHANGES: End
//
//////////////////////////////////////////////////////////////////////////////////////////////////

#if !defined(AFX_SCOTAPPDLG_H__C902752A_676E_11D1_82FB_F81607C1B845__INCLUDED_)
#define AFX_SCOTAPPDLG_H__C902752A_676E_11D1_82FB_F81607C1B845__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif  // _MSC_VER >= 1000

/////////////////////////////////////////////////////////////////////////////
// CSCOTAPPDlg dialog

class CSCOTAPPDlg : public CDialog
{
  // Construction
public:
  CSCOTAPPDlg(CWnd* pParent = NULL);	// standard constructor
  BOOL LoadPOSAssistMode();
	
#ifdef _DEBUG
  enum { IDD = IDD_SCOTAPP_DEBUG };
#else
  enum { IDD = IDD_SCOTAPP_RELEASE };
#endif
	
  // Dialog Data
  //{{AFX_DATA(CSCOTAPPDlg)
  // NOTE: the ClassWizard will add data members here
  //}}AFX_DATA
	
  // ClassWizard generated virtual function overrides
  //{{AFX_VIRTUAL(CSCOTAPPDlg)
	protected:
  virtual void DoDataExchange(CDataExchange* pDX); // DDX/DDV support
	//}}AFX_VIRTUAL
	
  // Implementation
protected:
  HICON m_hIcon;
  bool m_bLoadPOSAssistMode;
	
  // Generated message map functions
  //{{AFX_MSG(CSCOTAPPDlg)
  virtual BOOL OnInitDialog();
  afx_msg void OnSysCommand(UINT nID, LPARAM lParam);
  afx_msg void OnPaint();
  afx_msg HCURSOR OnQueryDragIcon();
  afx_msg void OnCancel();
  afx_msg LONG OnUserMessage(UINT,LONG);
  afx_msg LONG OnUserMessage2(UINT,LONG);
  afx_msg void OnTimer(UINT);
  afx_msg void OnSize(UINT nType, int cx, int cy);
  afx_msg LONG OnPutSCOTinLC(UINT, LONG);
  afx_msg LONG OnStopSCOT(UINT, LONG);
  afx_msg LONG OnQuerySCOTState(UINT, LONG);
  afx_msg LONG OnPowerStopSCOT(UINT, LONG);
  afx_msg LONG OnGetSCOTText(UINT, LONG); //+dp185016 rfc 365463
  afx_msg LONG OnGetDiagFiles(UINT, LONG); //-dp185016

  //}}AFX_MSG
	
	virtual LRESULT WindowProc(UINT message, WPARAM wParam, LPARAM lParam);
	
  CWnd* FindTaskWindow(CString csWindowName, bool bSearchFromEnd, DWORD dwProcessId, bool bUsePid);
  DECLARE_MESSAGE_MAP()
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif  // !defined(AFX_SCOTAPPDLG_H__C902752A_676E_11D1_82FB_F81607C1B845__INCLUDED_)
