#if !defined(AFX_SECURITYAGENT_H__68EE264A_E56C_11D3_BBA9_00A0C9EDD466__INCLUDED_)
#define AFX_SECURITYAGENT_H__68EE264A_E56C_11D3_BBA9_00A0C9EDD466__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSecurityAgent wrapper class

class CSecurityAgent : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSecurityAgent)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xe245ce83, 0xcc75, 0x11d0, { 0xa3, 0x86, 0x0, 0xe0, 0x29, 0x5, 0x87, 0x6b } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	BOOL GetOnline();
	void SetOnline(BOOL);
	long GetStatus();
	void SetStatus(long);
	BOOL Get_Online();
	void Set_Online(BOOL);
	long GetSchedule();
	void SetSchedule(long);
	long GetSecurityLevel();
	void SetSecurityLevel(long);
	long GetState();
	void SetState(long);
	short GetMode();
	void SetMode(short);
	long GetTimers();
	void SetTimers(long);
	BOOL GetTimersEnabled();
	void SetTimersEnabled(BOOL);
	BOOL GetSimulated();
	void SetSimulated(BOOL);
	BOOL GetServerEnabled();
	void SetServerEnabled(BOOL);
	CString GetServerName();
	void SetServerName(LPCTSTR);
	long GetServerConfiguration();
	void SetServerConfiguration(long);
	long GetServerStatus();
	void SetServerStatus(long);
	long GetClientConfiguration();
	void SetClientConfiguration(long);

// Operations
public:
	BOOL VoidRatioOK(long GrossSales, long VoidSales);
	BOOL ClearVoidTallies();
	BOOL ClearOtherTallies();
	BOOL SendSCOTInput(long ID, long Department, LPCTSTR UPC, long Weight, long Price, long Quantity);
	BOOL SendScaleInput(long Weight, long ReturnCode, long ReturnCodeExt);
	BOOL TransactionAbortOk(long GrossSales);
	BOOL CouponRatioOK(long GrossSales, long CouponTotals, long Type);
	BOOL ClearCouponTallies(long Amount, long Type);
	BOOL QuerySMMTol(LPCTSTR csUPC, long lDept, long lTolType, long lPPWU);
	BOOL UpdateSMMTol(long lAction, LPCTSTR csUPC, long lDept, long lTolType, long lWtExp, long lWtSubCk, long lWtTol, long lPPWU);
	BOOL QuerySMMWLDBwt(LPCTSTR csUPC, long lDept, LPCTSTR csDesc, long lPrice, long lSpecialItem, long lPPWU);
	BOOL UpdateSMMWLDBwt(long lAction, LPCTSTR csUPC, long lDept, long lBSwt, long lAppr, long lTally, long lDate, long lInitWt, long lPPWU);
	BOOL SendSCOTInputWithOverrides(long ID, long Dept, LPCTSTR UPC, long Weight, long Price, long Quantity, long lRequireSecBagging, long lRequireSecSubstChk);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SECURITYAGENT_H__68EE264A_E56C_11D3_BBA9_00A0C9EDD466__INCLUDED_)
